<?php
/**
 * Valkyrie Peptides' own product-tab content and one-off bulk-creator
 * definitions - the actual site-specific data behind the generic tools in
 * class-product-tools.php. Kept in its own file (rather than baked into the
 * tools class) so the plugin itself stays reusable, the same way
 * aera-frontend has zero business-specific data of its own: everything
 * here is wired in purely via the vrouter_product_tab_data /
 * vrouter_*_products filters those tools already expose.
 *
 * Not relevant to a fresh install of this plugin on a different site/catalog
 * - delete this file (and its one require_once line in valkyrie-router.php)
 * if you're deploying the router without Valkyrie's own product data.
 *
 * Content unchanged from the pre-rewrite valkyrie-router.php.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_filter( 'vrouter_product_tab_data', function () {
	return [
		133  => [ 'name' => 'TESAMORELIN – 10MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2024/09/1773253842237-3b359788-7187-42c5-a47b-b9efd3fab57b_1.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2024/09/1773253842237-3b359788-7187-42c5-a47b-b9efd3fab57b_2.jpg' ], 'info' => 'Tesamorelin — GHRH Analogue for Endocrine & Metabolic Research. Tesamorelin is a synthetic growth hormone–releasing hormone (GHRH) analogue widely examined in laboratory research for its role in growth hormone (GH) axis signaling and systemic metabolic regulation. Valkyrie Peptides supplies Tesamorelin as a lyophilized research-grade compound. Research areas: Mechanisms governing GH-axis stimulation and downstream IGF-1 signaling | Metabolic regulation involving lipid mobilization and energy-balance pathways | Endocrine-driven changes in tissue composition | Interactions between GH signaling and neuronal or cognitive pathways. Format: Lyophilized powder. For laboratory research use only.' ],
		124  => [ 'name' => 'GLP-3 (RT) – 30MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2024/09/VP-4892263-Retatrutide-Purity_page-0001.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2024/09/VP-4892263-Retatrutide-Purity_page-0002.jpg' ], 'info' => 'GLP-3 (RT) — Multi-Receptor Research Peptide. GLP-3 (RT) (also referenced as GLP3-RTA or LY-3437943) is a synthetic research peptide evaluated in advanced metabolic and endocrine signaling models. Characterised by interaction with GLP-1, GIP, and glucagon receptor pathways. Provided as lyophilized powder by Valkyrie Peptides. For laboratory research use only.' ],
		128  => [ 'name' => 'NAD+ – 500MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2024/09/VP-6801827-NAD-Purity-images-0-scaled.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2024/09/VP-6801827-NAD-Purity-images-1-scaled.jpg' ], 'info' => 'NAD+ (Nicotinamide Adenine Dinucleotide) — Cellular Energy & Redox Research Compound (500 mg). NAD+ is a fundamental coenzyme widely examined for its central role in cellular energy metabolism and oxidation-reduction (redox) signaling. Research areas: Electron-transfer reactions essential to metabolic flux | Regulation of oxidative and reductive states within cells | Support of enzymatic pathways tied to cellular repair and adaptation | Mechanisms underlying metabolic resilience and energy-production efficiency. Format: 500 mg lyophilized powder. For laboratory research use only.' ],
		131  => [ 'name' => 'GHK-Cu – 100MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2024/09/VP-4215641-GHK-Cu-Purity-images-0-scaled.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2024/09/VP-4215641-GHK-Cu-Purity-images-1-scaled.jpg' ], 'info' => 'GHK-Cu — Copper Tripeptide Research Compound. GHK-Cu is a copper-binding tripeptide complex widely examined in laboratory research for its involvement in extracellular matrix (ECM) signaling, cellular repair pathways, and redox-related biological processes. Research areas: Gene-expression patterns related to tissue repair and remodeling | Cellular migration and structural adaptation within connective-tissue models | Mechanisms underlying inflammation resolution and antioxidant defense | Cutaneous regeneration pathways and ECM-driven cellular communication. Format: Lyophilized powder. For laboratory research use only.' ],
		135  => [ 'name' => 'GLOW – 70MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2024/09/VP-1143805-GLOW-Purity_page-0001.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2024/09/VP-1143805-GLOW-Purity_page-0002.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2024/09/VP-1143805-GLOW-Purity_page-0003.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2024/09/VP-1143805-GLOW-Purity_page-0004.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2024/09/VP-1143805-GLOW-Purity_page-0005.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2024/09/VP-1143805-GLOW-Purity_page-0006.jpg' ], 'info' => 'GLOW — Multi-Component Research Peptide Blend (GHK-Cu 50mg + TB-500 10mg + BPC-157 10mg). Total 70mg per vial in lyophilized form. Components: GHK-Cu (50mg) — fibroblast activation, ECM regulation, antioxidant activity, gene-expression patterns linked to tissue remodeling | TB-500 (10mg) — cellular migration, structural recovery, cytoskeletal organization within soft-tissue models | BPC-157 (10mg) — microvascular signaling, inflammatory modulation, gastrointestinal or connective-tissue repair pathways. Format: Lyophilized powder. For laboratory research use only.' ],
		137  => [ 'name' => 'WOLVERINE – 20MG', 'coa' => [], 'info' => 'WOLVERINE — Dual-Peptide Research Blend (BPC-157 10mg + TB-500 10mg). Total 20mg per vial in lyophilized form. BPC-157 (10mg) — gastric-derived pentadecapeptide studied for angiogenic and microvascular signaling, collagen organization and ECM stability, inflammatory-pathway modulation and cytokine balance, epithelial integrity and nitric-oxide–related signaling. TB-500 (10mg) — synthetic fragment of thymosin beta-4, examined for actin-mediated cell migration and cytoskeletal organization, soft-tissue signaling and structural recovery, ECM remodeling and tissue-repair dynamics. Format: Lyophilized powder. For laboratory research use only.' ],
		139  => [ 'name' => 'MOTS-C – 10MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2024/09/VP-8066324-MOTS-c-Purity-images-0-scaled.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2024/09/VP-8066324-MOTS-c-Purity-images-1-scaled.jpg' ], 'info' => 'MOTS-C — Mitochondria-Derived Research Peptide. MOTS-C is a mitochondria-encoded peptide widely examined in laboratory research for its role in cellular energy regulation, metabolic signaling, and stress-response pathways. Research areas: AMPK-related signaling and downstream metabolic pathways | Mechanisms of mitochondrial communication and peptide-mediated regulation | Cellular responses to metabolic stress, nutrient shifts, and aging-related signaling | Bioenergetic adaptations associated with exercise-mimetic models. Format: Lyophilized powder. For laboratory research use only.' ],
		5397 => [ 'name' => 'Sermorelin – 10MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2026/03/VP-9912173-Sermorelin-Purity_page-0001.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/03/VP-9912173-Sermorelin-Purity_page-0002.jpg' ], 'info' => 'Sermorelin (GHRH 1-29) — Growth Hormone Axis Research Peptide. Sermorelin is a synthetic analogue of GHRH fragment 1-29, widely utilized in controlled research settings to investigate pituitary-driven GH signaling. Its activity is defined by selective interaction with GHRH receptors, initiating downstream pathways associated with physiological, pulsatile GH secretion. Format: 10mg lyophilized powder. For laboratory research use only.' ],
		5398 => [ 'name' => 'CJC-1295+Ipamorelin – 10MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2026/03/VP-9271992-CJC-1295-no-DAC-Purity_page-0001.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/03/VP-9271992-CJC-1295-no-DAC-Purity_page-0002.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/03/VP-9271992-CJC-1295-no-DAC-Purity_page-0003.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/03/VP-9271992-CJC-1295-no-DAC-Purity_page-0004.jpg' ], 'info' => 'CJC-1295 (No DAC) 5mg + Ipamorelin 5mg — Dual GH-Pathway Research Peptide. Total 10mg per vial in lyophilized form. CJC-1295 No DAC (GHRH analogue) + Ipamorelin (GHRP) combination enables researchers to evaluate: Frequency and amplitude changes in GH secretion | Synergistic effects on endocrine feedback loops | Broader impacts on metabolic, anabolic, and recovery-related pathways. Format: Lyophilized powder. For laboratory research use only.' ],
		5399 => [ 'name' => 'BPC-157 – 10MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2026/03/VP-6704696-BPC-157-Purity_page-0001.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/03/VP-6704696-BPC-157-Purity_page-0002.jpg' ], 'info' => 'BPC-157 (Body Protection Compound-157) — Research Peptide. Synthetic peptide modeled after a naturally occurring protein fragment found in gastric tissue. Research areas: Musculoskeletal injury and repair (tendon, ligament, muscle studies) | Gastrointestinal lining support including mucosal injury and inflammation models | Post-surgical recovery frameworks | Inflammation-related conditions. Not FDA approved for any medical indication. For laboratory research use only.' ],
		5400 => [ 'name' => 'TB-500 – 10MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2026/03/VP-9645060-TB-500-Purity_page-0001.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/03/VP-9645060-TB-500-Purity_page-0002.jpg' ], 'info' => 'TB-500 — Research Peptide. Synthetic peptide modeled after thymosin beta-4, a naturally occurring protein present in most mammalian cells. Research areas: Muscle, tendon, and ligament injury models | Joint and soft-tissue inflammation studies | Wound-healing and tissue-repair frameworks | Post-operative recovery research | Cardiovascular tissue repair (early animal studies). For laboratory research use only.' ],
		5401 => [ 'name' => 'PT-141 – 10MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2026/03/VP-4885039-PT-141-Purity_page-0001.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/03/VP-4885039-PT-141-Purity_page-0002.jpg' ], 'info' => 'PT-141 (Bremelanotide) — Neuromodulatory Research Peptide. Synthetic peptide studied for its interaction with central melanocortin receptors, particularly within neurological pathways associated with behavioral and neuroendocrine responses. Characteristics: Receptor-specific activation within CNS | Rapid onset of neuromodulatory effects | Activity across both male and female research subjects | Duration of receptor-mediated responses may extend several hours. Not approved for human or veterinary use. Format: Lyophilized powder. For laboratory research use only.' ],
		5879 => [ 'name' => 'SEMAX – 10MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2026/03/Screenshot-2026-03-31-153356.png', 'https://valkyriepeptides.com/wp-content/uploads/2026/03/Screenshot-2026-03-31-153418.png' ], 'info' => 'SEMAX — Neuroregulatory Research Peptide. Mechanistic areas: BDNF and NGF-related pathways supporting investigations into neuronal development and synaptic regulation | Neurochemical balance and CNS homeostasis including models of cognitive processing and neural adaptation | Oxidative-stress and hypoxia-response mechanisms | HPA-axis signaling evaluating stress-related endocrine modulation | Energy-metabolism pathways within neural tissue. Amino Acid Sequence: Met-Glu-His-Phe-Pro-Gly-Pro | Molecular Formula: C37H51N9O10S | Molecular Weight: 869.93 g/mol | Form: White lyophilized powder. Format: Lyophilized powder. For laboratory research use only.' ],
		5889 => [ 'name' => 'GLP-1 (SM) – 10MG', 'coa' => [], 'info' => 'GLP-1 SM (Semaglutide) — GLP-1 Receptor Agonist Research Peptide (10mg). Synthetic GLP-1 receptor agonist, high-purity lyophilized powder for controlled laboratory research. ≥99% purity. Structural characteristics: High GLP-1R affinity | Resistance to DPP-4 degradation | Extended stability via C-18 fatty-diacid acylation | Engagement of PI3K/Akt-related pathways | CNS-associated receptor activity including hypothalamic signaling. Research areas: Metabolic homeostasis | Neuroprotective and CNS-related pathways | Hepatic and metabolic-stress frameworks | Vascular and endothelial integrity. Storage: -20°C. For laboratory research use only.' ],
		5890 => [ 'name' => 'GLP-2 (TZ) – 30MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2026/04/VP-9305820-Tirzepatide-Purity_page-0001.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/04/VP-9305820-Tirzepatide-Purity_page-0002.jpg' ], 'info' => 'GLP-2-TZ — Dual-Receptor Incretin Research Peptide. Synthetic peptide analogue studied for its interaction with GIP and GLP-1 receptors. Molecular Formula: C225H348N48O68 | Molecular Weight: 4813.5 g/mol | CAS Number: 2023788-19-2. Research areas: Dual agonism of GIP and GLP-1 receptors | Receptor-binding kinetics | Metabolic-adaptation models | CNS-associated signaling | Comparative incretin-analog research. Storage: -20°C. For laboratory research use only.' ],
		5897 => [ 'name' => 'GLP-3 (RT) – 10MG', 'coa' => [], 'info' => 'GLP-3 RT — Triple-Receptor Agonist Research Peptide. Synthetic multi-agonist peptide engineered to interact with GLP-1, GIP, and glucagon receptors. Receptor targets: GLP-1R | GIPR | GCGR. Molecular Weight: ~4.8–5.0 kDa. Research areas: Incretin & glucagon biology | Energy-balance and nutrient-responsive signaling | Hepatic metabolic-pathway regulation | Islet-cell receptor modulation | Neuroendocrine metabolic-axis integration. Purity: ≥98% (HPLC-verified). Storage: -20°C. For laboratory research use only.' ],
		5898 => [ 'name' => 'SLU-PP 332 – 5MG', 'coa' => [], 'info' => 'SLU-PP-332 — Synthetic Small-Molecule Research Compound. Non-peptide heterocyclic compound for use in controlled laboratory environments. Chemical Profile: Molecular Formula: C18H14N2O2 | Compound Class: Synthetic small-molecule | Molecular Weight: ~290 g/mol. Research areas: Small-molecule mechanistic studies | Biochemical pathway modeling | Synthetic compound comparison assays | In-vitro systems evaluating molecular interactions. Purity: ≥99% (HPLC-verified). For laboratory research use only.' ],
		5899 => [ 'name' => 'SELANK – 10MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2026/04/VP-9715345-Selank-Purity-images-0-scaled.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/04/VP-9715345-Selank-Purity-images-1-scaled.jpg' ], 'info' => 'SELANK — Neuroregulatory Research Peptide. Synthetic heptapeptide analogue derived from endogenous tetrapeptide tuftsin. Research areas: Neurotransmitter-modulating activity including GABAergic and serotonergic pathways | Neurotrophic-factor expression particularly BDNF-associated signaling | Stress-response regulation including HPA-axis-related transcriptional activity | Cognitive-associated signaling | Immune-related pathways including tuftsin-derived immunomodulatory mechanisms. Format: Lyophilized powder. For laboratory research use only.' ],
		5902 => [ 'name' => 'NAD+ – 1000MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2026/04/VP-6690114-NAD-Purity-images-0-scaled.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/04/VP-6690114-NAD-Purity-images-1-scaled.jpg' ], 'info' => 'NAD+ — Cellular Energy & Redox Research Coenzyme. NAD+ (Nicotinamide Adenine Dinucleotide) is an essential coenzyme examined for its central role in cellular energy metabolism, oxidation-reduction (redox) reactions, and DNA-repair-associated enzymatic pathways. Research areas: Electron-transport chain activity supporting mitochondrial respiration | Cofactor roles in the Krebs cycle | Sirtuin activation regulating stress response, inflammation, and metabolic homeostasis | PARP-mediated DNA repair | Age-related metabolic decline. Purity: ≥99% (HPLC-tested). Storage: 2–8°C. For laboratory research use only.' ],
		5905 => [ 'name' => 'MELANOTAN 1 – 10MG', 'coa' => [], 'info' => 'Melanotan-1 — alpha-MSH Analogue for Melanocortin-Receptor Research. Synthetic analogue of alpha-MSH. Molecular Formula: C78H111N21O19 | Molecular Weight: 1646.87 g/mol | Other Names: MT-1, Afamelanotide. Receptor targets: MC1R (pigmentation) | MC2R (adrenal signaling) | MC3R (energy homeostasis and appetite) | MC4R (CNS metabolic and behavioral signaling) | MC5R (exocrine pathways). Research focus: MC1R selective affinity | cAMP signaling | MITF expression | downstream enzymatic activity in melanin synthesis. Format: Lyophilized powder. For laboratory research use only.' ],
		5906 => [ 'name' => 'L-GLUTATHIONE – 1000MG', 'coa' => [], 'info' => 'L-Glutathione — Tripeptide Antioxidant Research Compound. Naturally occurring tripeptide composed of glutamine, cysteine, and glycine. Molecular Formula: C10H17N3O6S | Molecular Weight: ~307 g/mol. Research areas: Redox-cycling activity (reduced GSH and oxidized GSSG states) | Enzymatic cofactor roles including glutathione peroxidase and glutathione reductase pathways | Protection against reactive oxygen species (ROS) | Maintenance of genomic stability under oxidative conditions | Regulation of intracellular antioxidant networks. Purity: ≥99% (HPLC-verified). Storage: -20°C. For laboratory research use only.' ],
		5907 => [ 'name' => 'KLOW – 80MG', 'coa' => [ 'https://valkyriepeptides.com/wp-content/uploads/2026/04/VP-9089847-KLOW-Purity_page-0001.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/04/VP-9089847-KLOW-Purity_page-0002.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/04/VP-9089847-KLOW-Purity_page-0003.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/04/VP-9089847-KLOW-Purity_page-0004.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/04/VP-9089847-KLOW-Purity_page-0005.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/04/VP-9089847-KLOW-Purity_page-0006.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/04/VP-9089847-KLOW-Purity_page-0007.jpg', 'https://valkyriepeptides.com/wp-content/uploads/2026/04/VP-9089847-KLOW-Purity_page-0008.jpg' ], 'info' => 'KLOW — Multi-Peptide Research Blend (80mg). Blend: BPC-157 + GHK-Cu + TB-500 + KPV. Components: BPC-157 — extracellular-matrix dynamics, cell-migration pathways, gastrointestinal-associated research frameworks | GHK-Cu — copper-binding interactions, ECM-related signaling, oxidative-stress response pathways | TB-500 — actin-binding proteins, cytoskeletal organization, cell-motility research models | KPV — inflammatory-signaling pathways, immune-cell response profiles, peptide-mediated regulatory mechanisms. Format: Lyophilized powder. Storage: -20°C. For laboratory research use only.' ],
		5916 => [ 'name' => 'TESMORELIN IPA – 15MG', 'coa' => [], 'info' => 'Tesamorelin + Ipamorelin — Dual GH-Axis Research Peptide System. Tesamorelin (GHRH analogue): Stimulates pituitary GH release through GHRH-receptor activation | Influences IGF-1-related signaling pathways | Provides extended GH-pulse duration. Ipamorelin (selective GHS): Ghrelin-receptor-mediated GH-pulse initiation | Controlled GH-release patterns without affecting cortisol or prolactin | Comparative studies GHS vs GHRH analogues. Format: Lyophilized powder. For laboratory research use only.' ],
		5917 => [ 'name' => 'BAC WATER – 10ML', 'coa' => [], 'info' => 'Bacteriostatic Water (BAC Water) — 10mL Research-Grade Diluent. Sterile, non-pyrogenic aqueous solution preserved with 0.9% benzyl alcohol. Used for reconstitution and dilution of lyophilized research compounds. Key features: Sterile, non-pyrogenic | 0.9% benzyl alcohol preservative | Suitable for multi-entry use | Sealed 10mL vial. Volume: 10mL | Storage: Room temperature, protect from direct light. For laboratory research use only.' ],
		5918 => [ 'name' => 'GHRP-6 – 10MG', 'coa' => [], 'info' => 'GHRP-6 — Growth Hormone Releasing Peptide-6. Synthetic hexapeptide, growth hormone secretagogue (GHS). CAS: 87616-84-0 | Formula: C46H56N12O6 | MW: 873.03 g/mol | Sequence: His-D-Trp-Ala-Trp-D-Phe-Lys-NH2. Research areas: Activation of GHS-R1a initiating GH-release signaling | Hypothalamic pathway modulation including somatostatin-related inhibition models | Evaluation of pulsatile GH secretion patterns | Endocrine-regulated metabolic-signaling pathways. Storage: 2–8°C short-term, -20°C long-term. For laboratory research use only.' ],
		// COA updated June 2026 — Batch 260417IG13, QC 261333, Purity 99.76%, Endotoxin PASS
		5919 => [ 'name' => 'IGF-1 LR3 – 1MG', 'coa' => [
			'https://valkyriepeptides.com/wp-content/uploads/2026/06/VP-261333-IGF-1LR3-Purity_page-0001.jpg',
			'https://valkyriepeptides.com/wp-content/uploads/2026/06/VP-261333-IGF-1LR3-Purity_page-0002.jpg',
		], 'info' => 'IGF-1 LR3 — Long R3 Insulin-Like Growth Factor-1 (1mg). Synthetic 83-amino-acid polypeptide, long-acting analogue of endogenous IGF-1. Structural modifications: extended N-terminal region and substitution of arginine at position 3 for reduced IGFBP binding. Research areas: Reduced affinity for IGF-binding proteins | Extended N-terminal structure with altered receptor-binding kinetics | Autocrine and paracrine signaling models | Tissue-distribution patterns. Purity: ≥99.76% (HPLC-verified, MDx BioAnalytical Labs, Batch 260417IG13). Storage: 2–8°C (long-term: -20°C). For laboratory research use only.' ],
		5939 => [ 'name' => 'IGF-1 LR3 – 1MG (Copy)', 'coa' => [], 'info' => 'IGF-1 LR3 — Long R3 Insulin-Like Growth Factor-1 (1mg). Synthetic 83-amino-acid polypeptide, long-acting analogue of endogenous IGF-1. Research areas: Reduced affinity for IGF-binding proteins | Autocrine and paracrine signaling models | Tissue-distribution patterns. Storage: 2–8°C (long-term: -20°C). For laboratory research use only.' ],

		// ── NEW PRODUCTS (May 2026) — placeholder IDs, replace after Bulk Create ──
		0 => [ 'name' => 'THYMOSIN ALPHA-1 – 10MG', 'coa' => [], 'info' => 'Thymosin Alpha-1 (Tα1) — Immune-Modulating Research Peptide. Naturally occurring 28-amino-acid peptide originally isolated from thymic tissue. Molecular Formula: C129H215N33O55 | Molecular Weight: 3,108.4 g/mol | CAS: 62304-98-7. Receptor targets: Toll-like receptors (TLR2, TLR9) | T-cell surface receptors. Research areas: CD4+/CD8+ T-lymphocyte maturation and immune-response initiation | Dendritic cell activation and antigen presentation | Pro/anti-inflammatory cytokine balance (IL-2, IFN-γ) | Innate immune signaling pathways. Purity: ≥99% (HPLC-verified). Storage: -20°C. For laboratory research use only.' ],
		1 => [ 'name' => 'HEXARELIN – 10MG', 'coa' => [], 'info' => 'Hexarelin — Growth Hormone Secretagogue Research Peptide. Synthetic hexapeptide, potent GHS-R1a agonist. CAS: 140703-51-1 | Formula: C47H58N12O6 | MW: 887.1 g/mol | Sequence: His-D-2-MeTrp-Ala-Trp-D-Phe-Lys-NH2. Research areas: Pulsatile GH release via GHSR-1a activation | Somatotroph cell function and GH pulse amplitude | GHS receptor selectivity profiling | Cardiovascular tissue models with GHS receptor activity. Purity: ≥99% (HPLC-verified). Storage: -20°C. For laboratory research use only.' ],
		2 => [ 'name' => 'OXYTOCIN – 5MG', 'coa' => [], 'info' => 'Oxytocin — Neuropeptide Hormone Research Compound. Cyclic nonapeptide produced in the hypothalamus. Molecular Formula: C43H66N12O12S2 | Molecular Weight: 1,007.2 g/mol | CAS: 50-56-6 | Sequence: Cys-Tyr-Ile-Gln-Asn-Cys-Pro-Leu-Gly-NH2. Research areas: Hypothalamic hormone release and neuropeptide receptor-binding kinetics | Social behavior and prosocial signaling in in-vitro and animal models | Myometrial smooth muscle contractility and parturition-related endocrine pathways | HPA-axis interaction and anxiolytic pathway modulation. Purity: ≥99% (HPLC-verified). Storage: -20°C. For laboratory research use only.' ],
		3 => [ 'name' => 'KISSPEPTIN-10 – 10MG', 'coa' => [], 'info' => 'Kisspeptin-10 — GPR54 Receptor Agonist Neuroendocrine Research Peptide. Biologically active C-terminal decapeptide of the kisspeptin family. Molecular Formula: C63H83N15O13 | Molecular Weight: 1,302.5 g/mol | Sequence: Tyr-Asn-Trp-Asn-Ser-Phe-Gly-Leu-Arg-Phe-NH2. Research areas: HPG-axis upstream GnRH pulse regulation | GPR54 (KISS1R) receptor binding kinetics and internalization | LH and FSH secretion dynamics and gonadotropin pulse regulation | Metabolic hormone cross-talk and energy homeostasis signaling. Purity: ≥99% (HPLC-verified). Storage: -20°C. For laboratory research use only.' ],
		4 => [ 'name' => 'AOD-9604 – 5MG', 'coa' => [], 'info' => 'AOD-9604 — hGH Fragment 177-191 Metabolic Research Peptide. Synthetic analogue of C-terminal fragment of human growth hormone. Molecular Formula: C78H123N23O23S2 | Molecular Weight: 1,816.1 g/mol | Disulfide bridge: Cys182-Cys189. Research areas: Lipolysis stimulation and lipogenesis inhibition via non-GHR mechanisms | Comparative hGH C-terminal fragment vs. full-length GH receptor binding | Articular cartilage repair signaling and chondrocyte regeneration models | β3-adrenoceptor-mediated metabolic effects in adipocyte models. Purity: ≥99% (HPLC-verified). Storage: -20°C. For laboratory research use only.' ],
		5 => [ 'name' => 'MELANOTAN II – 10MG', 'coa' => [], 'info' => 'Melanotan II (MT-II) — Cyclic alpha-MSH Analogue for Melanocortin Receptor Research. Synthetic cyclic analogue of alpha-MSH with enhanced receptor affinity. Molecular Formula: C50H69N15O9 | Molecular Weight: 1,024.2 g/mol | CAS: 121062-08-6 | Sequence: Ac-Nle-c[Asp-His-D-Phe-Arg-Trp-Lys]-OH (cyclic). Receptor targets: MC1R (pigmentation) | MC3R (energy homeostasis) | MC4R (CNS metabolic/behavioral) | MC5R (exocrine). Research areas: Melanogenesis signaling, MITF expression, eumelanin/pheomelanin switching | Hypothalamic appetite regulation via MC4R | Neuroendocrine arousal pathway studies | Comparative cyclic vs. linear MSH analogue receptor affinity. Purity: ≥99% (HPLC-verified). Storage: -20°C. For laboratory research use only.' ],

		// ── NEW PRODUCTS (June 2026) — placeholder IDs, replace after Bulk Create ──
		6  => [ 'name' => 'EPITALON – 50MG', 'coa' => [
			'https://valkyriepeptides.com/wp-content/uploads/2026/06/VP-260878-Epitalon-Purity_page-0001.jpg',
			'https://valkyriepeptides.com/wp-content/uploads/2026/06/VP-260878-Epitalon-Purity_page-0002.jpg',
		], 'info' => 'Epitalon (Epithalon) — Telomere-Targeting Tetrapeptide Research Compound. Synthetic tetrapeptide (Ala-Glu-Asp-Gly) originally isolated from bovine pineal gland extract. Molecular Formula: C14H22N4O9 | Molecular Weight: 390.34 g/mol | CAS: 307297-39-8. Research areas: Telomerase activation and telomere length regulation in cellular aging models | Pineal gland-mediated melatonin synthesis and circadian rhythm-associated pathways | Age-related endocrine adaptation including IGF-1 and cortisol axis interactions | Replicative senescence and cell-cycle checkpoint models. Purity: ≥99.76% (HPLC-verified, MDx BioAnalytical Labs, Batch 26022EP505). Storage: -20°C. For laboratory research use only.' ],
		7  => [ 'name' => 'CAGRILINTIDE – 10MG', 'coa' => [
			'https://valkyriepeptides.com/wp-content/uploads/2026/06/VP-QC260277-Cagrilintide-Purity_page-0001.jpg',
			'https://valkyriepeptides.com/wp-content/uploads/2026/06/VP-QC260277-Cagrilintide-Purity_page-0002.jpg',
		], 'info' => 'Cagrilintide — Long-Acting Amylin/Calcitonin Receptor Agonist Research Peptide. Synthetic long-acting acylated amylin analogue with dual activity at amylin and calcitonin receptors. CAS: 2381065-73-0 | Molecular Weight: ~6.1 kDa. Research areas: Dual AMYR/calcitonin receptor agonism and satiety-pathway signaling | Calcitonin receptor-mediated calcium metabolism and bone homeostasis models | Amylin/GLP-1 receptor co-agonist pharmacodynamics | CNS appetite-circuit modulation via hypothalamic pathways. Purity: ≥99.75% (HPLC-verified, MDx BioAnalytical Labs, Batch 260114CG103). Storage: -20°C. For laboratory research use only.' ],
		8  => [ 'name' => 'DSIP – 5MG', 'coa' => [
			'https://valkyriepeptides.com/wp-content/uploads/2026/06/VP-QC250961-DSIP-Purity_page-0001.jpg',
			'https://valkyriepeptides.com/wp-content/uploads/2026/06/VP-QC250961-DSIP-Purity_page-0002.jpg',
		], 'info' => 'DSIP (Delta Sleep-Inducing Peptide) — Neuromodulatory Research Nonapeptide. Endogenous nonapeptide first isolated from venous blood of sleeping rabbits. Molecular Formula: C35H48N10O15 | Molecular Weight: 848.8 g/mol | CAS: 62568-57-4 | Sequence: Trp-Ala-Gly-Gly-Asp-Ala-Ser-Gly-Glu. Research areas: Hypothalamic modulation of slow-wave (delta) sleep architecture | Neuromodulatory interactions with GABAergic and serotonergic pathways | HPA-axis regulation including ACTH and corticotropin-related signaling | Stress-response attenuation and circadian rhythm-associated pathway modulation. Purity: ≥99.90% (HPLC-verified, MDx BioAnalytical Labs, Sample 287). Storage: -20°C. For laboratory research use only.' ],
		9  => [ 'name' => '5-AMINO-1MQ – 50MG', 'coa' => [], 'info' => '5-Amino-1MQ — NNMT Inhibitor Small-Molecule Research Compound. Synthetic N-methylquinolinium derivative studied as a selective inhibitor of nicotinamide N-methyltransferase (NNMT), an enzyme central to cellular methylation balance and metabolic regulation. Compound class: Small-molecule NNMT inhibitor | Molecular Weight: ~174 g/mol. Research areas: NNMT enzyme inhibition kinetics and SAM (S-adenosylmethionine) methylation pathway modulation | Adipocyte differentiation and lipid metabolism in cellular models | NAD+ precursor availability and cellular energy-regulation pathways | Metabolic adaptation frameworks including obesity and aging-related models. Purity: ≥99% (HPLC-verified). Storage: -20°C. Format: Lyophilized powder. For laboratory research use only.' ],
		10 => [ 'name' => 'GAC WATER – 10ML', 'coa' => [], 'info' => 'GAC Water — Sterile Research-Grade Reconstitution Diluent (10mL). Sterile, non-pyrogenic aqueous solution for the reconstitution and dilution of lyophilized research peptides and compounds. Preserved with benzyl alcohol for multi-entry vial use. Key features: Sterile, non-pyrogenic | Benzyl alcohol preservative | Suitable for multi-entry use | Sealed 10mL vial. Volume: 10mL | Storage: Room temperature, protect from direct light. For laboratory research use only.' ],

		// ── NEW PRODUCTS (July 2026) — placeholder IDs, replace after Create SS-31/CJC ──
		11 => [ 'name' => 'SS-31 – 50MG', 'coa' => [
			'https://valkyriepeptides.com/wp-content/uploads/2026/07/Batch-260326SS505SP-SS-31.pdf',
		], 'info' => 'SS-31 (Elamipretide) — Mitochondria-Targeting Tetrapeptide Research Compound (50mg). Synthetic aromatic-cationic tetrapeptide studied for selective cardiolipin binding on the inner mitochondrial membrane. Research areas: Electron-transport-chain efficiency and ATP-synthesis pathway studies | Oxidative-stress and ROS-reduction models | Ischemia-reperfusion injury research | Age-related mitochondrial dysfunction models. Sequence: D-Arg-2\',6\'-Dmt-Lys-Phe-NH2. Purity: ≥99.76% (HPLC-verified, MDx BioAnalytical Labs, Batch 260326SS505SP). Endotoxin: PASS. Storage: -20°C. Format: Lyophilized powder. For laboratory research use only.' ],
		12 => [ 'name' => 'CJC-1295+Ipamorelin – 20MG', 'coa' => [
			'https://valkyriepeptides.com/wp-content/uploads/2026/07/Batch-260331CI103-CJC-1295-NO-DACIPAMORELIN.pdf',
		], 'info' => 'CJC-1295 (No DAC) 10mg + Ipamorelin 10mg — Dual GH-Pathway Research Peptide. Total 20mg per vial in lyophilized form. CJC-1295 No DAC (GHRH analogue) + Ipamorelin (GHRP) combination enables researchers to evaluate: Frequency and amplitude changes in GH secretion | Synergistic effects on endocrine feedback loops | Broader impacts on metabolic, anabolic, and recovery-related pathways. Purity: ≥99.77% (HPLC-verified, MDx BioAnalytical Labs, Batch 260331CI103). Endotoxin: PASS. Storage: -20°C. Format: Lyophilized powder. For laboratory research use only.' ],

		// ── NEW PRODUCTS (Aug 2026) — placeholder IDs, replace after Create GLP-2/KPV ──
		// GLP-2 (TZ) 10MG is a size-variant sibling of the existing GLP-2 (TZ) 30MG
		// product (id 5890) - the frontend's VARIANT_GROUPS wiring links them.
		13 => [ 'name' => 'GLP-2 (TZ) – 10MG', 'coa' => [], 'info' => 'GLP-2-TZ — Dual-Receptor Incretin Research Peptide (10mg). Synthetic peptide analogue studied for its interaction with GIP and GLP-1 receptors. Molecular Formula: C225H348N48O68 | Molecular Weight: 4813.5 g/mol | CAS Number: 2023788-19-2. Research areas: Dual agonism of GIP and GLP-1 receptors | Receptor-binding kinetics | Metabolic-adaptation models | CNS-associated signaling including hypothalamic receptor engagement | Comparative incretin-analog research. Storage: -20°C. For laboratory research use only.' ],
		14 => [ 'name' => 'KPV – 10MG', 'coa' => [], 'info' => 'KPV (Lysine-Proline-Valine) — C-Terminal Alpha-MSH Fragment Research Peptide (10mg). Synthetic tripeptide derived from the C-terminal sequence of alpha-melanocyte-stimulating hormone (alpha-MSH). Research areas: Anti-inflammatory signaling pathways independent of melanocortin-receptor activation | NF-κB pathway modulation | Cytokine-response research models | Gastrointestinal and dermal inflammatory-signaling studies. Format: Lyophilized powder. For laboratory research use only.' ],
	];
} );

add_filter( 'vrouter_ghrp_igf_products', function () {
	return [
		'ghrp-6-10mg' => [
			'name'              => 'GHRP-6 – 10MG',
			'price'             => '60.00',
			'sku'               => 'VK-GHRP6-10MG',
			'short_description' => 'GHRP-6 — growth hormone-releasing hexapeptide. 10mg lyophilized vial. ≥99% purity (HPLC). GHS-R1a agonist. Made in USA. For laboratory research use only.',
			'description'       => 'GHRP-6 (Growth Hormone-Releasing Hexapeptide) is a synthetic hexapeptide and potent GHS-R1a agonist that stimulates endogenous growth hormone secretion through ghrelin receptor activation. It is widely used in research exploring GH secretion dynamics, appetite regulation, and downstream anabolic signaling pathways.<br><br>Research areas: Pulsatile GH release via GHS-R1a activation and somatotroph cell function | Ghrelin mimetic activity and appetite/orexigenic pathway studies | Comparative GHRP selectivity profiling across the hexapeptide secretagogue family | GH/IGF-1 axis downstream signaling in in-vitro models.<br><br>Sequence: His-D-Trp-Ala-Trp-D-Phe-Lys-NH2 | CAS: 87616-84-0 | MW: 873.0 g/mol. Purity: ≥99% (HPLC-verified). Storage: -20°C. Format: Lyophilized powder. For laboratory research use only.',
			'image_url'         => '',
			'coa_purity_pdf'    => '',
			'coa_endotoxin_pdf' => '',
		],
		'igf-1-lr3-1mg' => [
			'name'              => 'IGF-1 LR3 – 1MG',
			'price'             => '95.00',
			'sku'               => 'VK-IGF1LR3-1MG',
			'short_description' => 'IGF-1 LR3 — Long R3 Insulin-Like Growth Factor-1. 1mg lyophilized vial. ≥99% purity (HPLC). 83-amino-acid long-acting IGF-1 analogue. Made in USA. For laboratory research use only.',
			'description'       => 'IGF-1 LR3 (Long R3 Insulin-Like Growth Factor-1) is a synthetic 83-amino-acid analogue of endogenous IGF-1, engineered with an N-terminal 13-amino-acid extension and a Arg³ substitution that dramatically reduces IGF-binding protein affinity, extending its biological half-life in research models.<br><br>Research areas: Reduced affinity for IGF-binding proteins (IGFBP-1 through IGFBP-6) and extended half-life studies | Autocrine and paracrine IGF-1 signaling model development | Tissue-distribution and receptor-binding kinetics vs. native IGF-1 | Myoblast and adipocyte differentiation pathway research.<br><br>COA: Batch 260417IG13 — Purity 99.76% (HPLC), Endotoxin PASS. Tested by MDx BioAnalytical Labs, 04 May 2026. Molecular Weight: ~9,117 Da. Storage: -20°C. Format: Lyophilized powder. For laboratory research use only.',
			'image_url'         => '',
			'coa_purity_pdf'    => '',
			'coa_endotoxin_pdf' => '',
		],
	];
} );

add_filter( 'vrouter_ss31_cjc_products', function () {
	return [
		'ss-31-50mg' => [
			'name'              => 'SS-31 – 50MG',
			'price'             => '185.00',
			'sku'               => 'VK-SS31-50MG',
			'short_description' => 'SS-31 (Elamipretide) — mitochondria-targeting tetrapeptide. 50mg lyophilized vial. ≥99.76% purity (HPLC). Cardiolipin-binding research peptide. Made in USA. For laboratory research use only.',
			'description'       => 'SS-31 (also referenced as Elamipretide or Bendavia) is a synthetic aromatic-cationic tetrapeptide widely examined in laboratory research for its selective binding to cardiolipin on the inner mitochondrial membrane and its role in mitochondrial bioenergetics.<br><br>Research areas: Cardiolipin-binding interactions and inner mitochondrial membrane stabilization | Electron-transport-chain efficiency and ATP-synthesis pathway studies | Oxidative-stress and reactive oxygen species (ROS) reduction models | Ischemia-reperfusion injury and age-related mitochondrial dysfunction research.<br><br>Sequence: D-Arg-2\',6\'-Dmt-Lys-Phe-NH2 | Molecular Formula: C36H49N9O5 | Molecular Weight: 639.83 g/mol.<br><br>Purity: ≥99.76% (HPLC-verified, MDx BioAnalytical Labs, Batch 260326SS505SP, COA261237). Endotoxin: PASS (≤0.05 EU/mL). Storage: -20°C. Format: Lyophilized powder. For laboratory research use only.',
			'image_url'         => 'https://valkyriepeptides.com/wp-content/uploads/2026/07/ss-31.jpeg',
			'coa_purity_pdf'    => 'https://valkyriepeptides.com/wp-content/uploads/2026/07/Batch-260326SS505SP-SS-31.pdf',
			'coa_endotoxin_pdf' => 'https://valkyriepeptides.com/wp-content/uploads/2026/07/Batch-260326SS505SP-SS-31.pdf',
		],
		'cjc-ipa-20mg' => [
			'name'              => 'CJC-1295+Ipamorelin – 20MG',
			'price'             => '150.00',
			'sku'               => 'VK-CJCIPA-20MG',
			'short_description' => 'CJC-1295 (No DAC) 10mg + Ipamorelin 10mg — dual GH-pathway research peptide blend. 20mg lyophilized vial. ≥99.77% purity (HPLC). Made in USA. For laboratory research use only.',
			'description'       => 'CJC-1295 (No DAC) 10mg + Ipamorelin 10mg is a dual-peptide research blend combining a GHRH analogue with a selective ghrelin-receptor agonist (GHRP). Total 20mg per vial in lyophilized form — double concentration of the standard 10mg formulation for extended research use.<br><br>CJC-1295 No DAC (GHRH analogue): Stimulates pituitary GH release through GHRH-receptor activation | Extended GH-pulse amplitude in comparative secretagogue studies.<br><br>Ipamorelin (selective GHS/GHRP): Ghrelin-receptor-mediated GH-pulse initiation | Minimal cross-reactivity with cortisol, prolactin, and ACTH pathways in research models.<br><br>Combined research areas: Frequency and amplitude changes in GH secretion | Synergistic effects on endocrine feedback loops | Broader impacts on metabolic, anabolic, and recovery-related pathways.<br><br>Purity: ≥99.77% (HPLC-verified, MDx BioAnalytical Labs, Batch 260331CI103, COA261291). Endotoxin: PASS (≤0.05 EU/mL). Storage: -20°C. Format: Lyophilized powder. For laboratory research use only.',
			'image_url'         => 'https://valkyriepeptides.com/wp-content/uploads/2026/07/cjc-ipa.jpeg',
			'coa_purity_pdf'    => 'https://valkyriepeptides.com/wp-content/uploads/2026/07/Batch-260331CI103-CJC-1295-NO-DACIPAMORELIN.pdf',
			'coa_endotoxin_pdf' => 'https://valkyriepeptides.com/wp-content/uploads/2026/07/Batch-260331CI103-CJC-1295-NO-DACIPAMORELIN.pdf',
		],
	];
} );

add_filter( 'vrouter_glp2_kpv_products', function () {
	return [
		'glp-2-tz-10mg' => [
			'name'              => 'GLP-2 (TZ) – 10MG',
			'price'             => '85.00',
			'sku'               => 'VK-GLP2TZ-10MG',
			'short_description' => 'GLP-2-TZ — Dual-Receptor Incretin Research Peptide. 10mg lyophilized vial. Studied for GIP/GLP-1 receptor interaction. Made in USA. For laboratory research use only.',
			'description'       => 'GLP-2-TZ is a synthetic peptide analogue studied for its interaction with GIP and GLP-1 receptors, provided here in a 10mg lyophilized vial — a smaller-dose sibling of our 30mg GLP-2 (TZ) formulation.<br><br>Research areas: Dual agonism of GIP and GLP-1 receptors | Receptor-binding kinetics | Metabolic-adaptation models | CNS-associated signaling including hypothalamic receptor engagement | Comparative incretin-analog research.<br><br>Molecular Formula: C225H348N48O68 | Molecular Weight: 4813.5 g/mol | CAS Number: 2023788-19-2. Storage: -20°C. Format: Lyophilized powder. For laboratory research use only.',
			'image_url'         => 'https://valkyriepeps.com/wp-content/uploads/2026/08/glp-2.png',
			'coa_purity_pdf'    => 'https://valkyriepeps.com/wp-content/uploads/2026/08/TZ-10mg-purity.pdf',
			'coa_endotoxin_pdf' => 'https://valkyriepeps.com/wp-content/uploads/2026/08/TZ-10mg-Endo.pdf',
		],
		'kpv-10mg' => [
			'name'              => 'KPV – 10MG',
			'price'             => '75.00',
			'sku'               => 'VK-KPV-10MG',
			'short_description' => 'KPV (Lysine-Proline-Valine) — C-terminal alpha-MSH fragment research tripeptide. 10mg lyophilized vial. Made in USA. For laboratory research use only.',
			'description'       => 'KPV is a synthetic tripeptide derived from the C-terminal sequence of alpha-melanocyte-stimulating hormone (alpha-MSH), studied for anti-inflammatory signaling independent of melanocortin-receptor activation.<br><br>Research areas: Anti-inflammatory signaling pathways independent of melanocortin-receptor activation | NF-κB pathway modulation | Cytokine-response research models | Gastrointestinal and dermal inflammatory-signaling studies.<br><br>Sequence: Lys-Pro-Val. Storage: -20°C. Format: Lyophilized powder. For laboratory research use only.',
			'image_url'         => 'https://valkyriepeps.com/wp-content/uploads/2026/08/WhatsApp_Image_2026-08-12_at_16.34.18-removebg-preview.png',
			'coa_purity_pdf'    => 'https://valkyriepeps.com/wp-content/uploads/2026/08/KPV-10mg-Purity.pdf',
			'coa_endotoxin_pdf' => 'https://valkyriepeps.com/wp-content/uploads/2026/08/KPV-10mg-Endo.pdf',
		],
	];
} );
